### ISSUE TITLE
Recipe docker::default does not exists anymore

### ISSUE THREAD

**Issue by PierreRambaud** [paulczar/cookbook-docker_registry#2]
Hi,

Docker cookbook just has a new update, there is no recipes directory anymore.
https://github.com/paulczar/cookbook-docker_registry/blob/master/recipes/webui.rb#L9

Regards

**Comment by PierreRambaud** [comment]
Gentle ping

**Comment by paulczar** [comment]
the docker cookbook on supermarket ( https://supermarket.chef.io/cookbooks/docker ) is still < 1.0 and the recipes etc should still work as Berkshelf should be using supermarket to determine which version to use.

**Comment by PierreRambaud** [comment]
Sure, but there is no directory `recipes` since the v0.40 (https://github.com/bflad/chef-docker/tree/v0.40.0) :/

**Comment by paulczar** [comment]
blarg! I didn't even notice that.

will need to lock it down to `'docker', '= 0.37.0'` in metadata.

**Comment by PierreRambaud** [comment]
Otherwise, you can remove the include_recipe call and use LWRPs?

Regards

**Comment by paulczar** [comment]
Right I've locked it down to the older docker cookbook for now and released a new version to supermarket.   I'll update it soon to use the new style and do a larger version bump.
